In [38]:
print('hello')

hello

In [39]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as pl

In [40]:
store = pd.DataFrame({
    'cust_id':[101,102,103,104,105,106],
    'cust_name':['Rahul','Rohit','Ram','Satish','Amit','Prashant'],
    'city':['Azamgarh','Sitapur','Azamgarh','Varanasi','Varanasi','Ambedkar nagar'],
    'product':['samsung','apple','apple','motorola','realme','oppo'],
    'price':[25000,35000,22000,40000,18000,23000],
    'quantity':[10,12,15,5,20,14]
})

In [41]:
store

   cust_id cust_name            city   product  price  quantity
0      101     Rahul        Azamgarh   samsung  25000        10
1      102     Rohit         Sitapur     apple  35000        12
2      103       Ram        Azamgarh     apple  22000        15
3      104    Satish        Varanasi  motorola  40000         5
4      105      Amit        Varanasi    realme  18000        20
5      106  Prashant  Ambedkar nagar      oppo  23000        14

In [42]:
store['total_amount'] = store['price']*store['quantity']
print(store)

   cust_id cust_name            city   product  price  quantity  total_amount
0      101     Rahul        Azamgarh   samsung  25000        10        250000
1      102     Rohit         Sitapur     apple  35000        12        420000
2      103       Ram        Azamgarh     apple  22000        15        330000
3      104    Satish        Varanasi  motorola  40000         5        200000
4      105      Amit        Varanasi    realme  18000        20        360000
5      106  Prashant  Ambedkar nagar      oppo  23000        14        322000

In [43]:
grouped = store.groupby('city')['total_amount'].mean()

In [44]:
grouped

city
Ambedkar nagar    322000.0
Azamgarh          290000.0
Sitapur           420000.0
Varanasi          280000.0
Name: total_amount, dtype: float64

In [45]:
grouped_max = store.groupby('city')['quantity'].max()
print(grouped_max)

city
Ambedkar nagar    14
Azamgarh          15
Sitapur           12
Varanasi          20
Name: quantity, dtype: int64

In [46]:
agg = store.groupby('product').agg({
    'price':['min','max','mean'],
    'total_amount':['mean']
})
print(agg)

          price                 total_amount
            min    max     mean         mean
product
apple     22000  35000  28500.0     375000.0
motorola  40000  40000  40000.0     200000.0
oppo      23000  23000  23000.0     322000.0
realme    18000  18000  18000.0     360000.0
samsung   25000  25000  25000.0     250000.0

In [47]:
size = store.groupby('city').size()
print(size)

city
Ambedkar nagar    1
Azamgarh          2
Sitapur           1
Varanasi          2
dtype: int64

In [48]:
customer = pd.DataFrame({
    'id' :[101,102,103],
    'name' :['roshan','vikash','prashant'],
    'marks' :[45,55,65] 
})
customers1 =pd.DataFrame({
    'id' :[101,102,104],
    'age' :[18,20,25],
    'class':[10,12,11]
})

In [49]:
merge = pd.merge(customer,customers1, on='id',how='inner')

In [50]:
merge

    id    name  marks  age  class
0  101  roshan     45   18     10
1  102  vikash     55   20     12

In [51]:
merge_left = pd.merge(customer,customers1, on='id',how='left')
print(merge_left)

    id      name  marks   age  class
0  101    roshan     45  18.0   10.0
1  102    vikash     55  20.0   12.0
2  103  prashant     65   NaN    NaN

In [52]:
merge_right = pd.merge(customer,customers1, on='id',how='right')
print(merge_right)

    id    name  marks  age  class
0  101  roshan   45.0   18     10
1  102  vikash   55.0   20     12
2  104     NaN    NaN   25     11

In [53]:
merge_outer = pd.merge(customer,customers1, on='id',how='outer')
print(merge_outer)

    id      name  marks   age  class
0  101    roshan   45.0  18.0   10.0
1  102    vikash   55.0  20.0   12.0
2  103  prashant   65.0   NaN    NaN
3  104       NaN    NaN  25.0   11.0

In [54]:
concatnate_column = pd.concat([customer,customers1],axis=0)
print(concatnate_column)

    id      name  marks   age  class
0  101    roshan   45.0   NaN    NaN
1  102    vikash   55.0   NaN    NaN
2  103  prashant   65.0   NaN    NaN
0  101       NaN    NaN  18.0   10.0
1  102       NaN    NaN  20.0   12.0
2  104       NaN    NaN  25.0   11.0

In [55]:
concatnate_rows = pd.concat([customer,customers1],axis=1)
print(concatnate_rows)

    id      name  marks   id  age  class
0  101    roshan     45  101   18     10
1  102    vikash     55  102   20     12
2  103  prashant     65  104   25     11

In [56]:
store

   cust_id cust_name            city   product  price  quantity  total_amount
0      101     Rahul        Azamgarh   samsung  25000        10        250000
1      102     Rohit         Sitapur     apple  35000        12        420000
2      103       Ram        Azamgarh     apple  22000        15        330000
3      104    Satish        Varanasi  motorola  40000         5        200000
4      105      Amit        Varanasi    realme  18000        20        360000
5      106  Prashant  Ambedkar nagar      oppo  23000        14        322000

In [57]:
pivot = store.pivot_table(values='total_amount', index='product', columns='cust_name', aggfunc='sum')

In [58]:
pivot

cust_name      Amit  Prashant     Rahul       Ram     Rohit    Satish
product
apple           NaN       NaN       NaN  330000.0  420000.0       NaN
motorola        NaN       NaN       NaN       NaN       NaN  200000.0
oppo            NaN  322000.0       NaN       NaN       NaN       NaN
realme     360000.0       NaN       NaN       NaN       NaN       NaN
samsung         NaN       NaN  250000.0       NaN       NaN       NaN

In [59]:
crosstab=pd.crosstab(store['cust_name'],store['quantity'])

In [60]:
crosstab

quantity   5   10  12  14  15  20
cust_name
Amit        0   0   0   0   0   1
Prashant    0   0   0   1   0   0
Rahul       0   1   0   0   0   0
Ram         0   0   0   0   1   0
Rohit       0   0   1   0   0   0
Satish      1   0   0   0   0   0